const rows = [
  {
    id: 1,
    disciplina: "Matemática",
    professor: "Carlos Oliveira",
    telefone: "(11) 98765-4321",
    email: "carlos.oliveira@email.com",
    dtAdmissao: "2021-03-15",
    salario: 4500,
    turno: "Manhã",
    status: "Ativo",
    Series: "6º ao 9º",
    proxFeedback: "2024-05-10",
    observacoes: "Ótima didática.",
    buttonAlert: "admin/dashboard/1",
    buttonEdit: "admin/dashboard/1",
  },
  {
    id: 2,
    disciplina: "Português",
    professor: "Fernanda Souza",
    telefone: "(21) 99876-5432",
    email: "fernanda.souza@email.com",
    dtAdmissao: "2019-08-22",
    salario: 5200,
    turno: "Tarde",
    status: "Ativo",
    Series: "Fundamental e Médio",
    proxFeedback: "2024-06-12",
    observacoes: "Especialista em literatura.",
    buttonAlert: "admin/dashboard/2",
    buttonEdit: "admin/dashboard/2",
  },
  {
    id: 3,
    disciplina: "História",
    professor: "Ricardo Lima",
    telefone: "(31) 98888-7777",
    email: "ricardo.lima@email.com",
    dtAdmissao: "2020-02-10",
    salario: 4800,
    turno: "Noite",
    status: "Ativo",
    Series: "Ensino Médio",
    proxFeedback: "2024-07-08",
    observacoes: "Trabalha com metodologias ativas.",
    buttonAlert: "admin/dashboard/3",
    buttonEdit: "admin/dashboard/3",
  },
  {
    id: 4,
    disciplina: "Geografia",
    professor: "Mariana Ferreira",
    telefone: "(41) 97777-6666",
    email: "mariana.ferreira@email.com",
    dtAdmissao: "2018-05-25",
    salario: 4700,
    turno: "Manhã",
    status: "Ativo",
    Series: "6º ao 9º",
    proxFeedback: "2024-08-15",
    observacoes: "Excelente trabalho com mapas interativos.",
    buttonAlert: "admin/dashboard/4",
    buttonEdit: "admin/dashboard/4",
  },
  {
    id: 5,
    disciplina: "Ciências",
    professor: "Daniel Alves",
    telefone: "(51) 96666-5555",
    email: "daniel.alves@email.com",
    dtAdmissao: "2017-09-18",
    salario: 5000,
    turno: "Tarde",
    status: "Ativo",
    Series: "Fundamental II",
    proxFeedback: "2024-09-20",
    observacoes: "Tem um laboratório bem equipado.",
    buttonAlert: "admin/dashboard/5",
    buttonEdit: "admin/dashboard/5",
  },
  {
    id: 6,
    disciplina: "Educação Física",
    professor: "Juliana Mendes",
    telefone: "(61) 95555-4444",
    email: "juliana.mendes@email.com",
    dtAdmissao: "2016-11-10",
    salario: 4600,
    turno: "Noite",
    status: "Ativo",
    Series: "1º ao 9º",
    proxFeedback: "2024-10-05",
    observacoes: "Lidera campeonatos esportivos.",
    buttonAlert: "admin/dashboard/6",
    buttonEdit: "admin/dashboard/6",
  },
  {
    id: 7,
    disciplina: "Física",
    professor: "Leonardo Santos",
    telefone: "(71) 94444-3333",
    email: "leonardo.santos@email.com",
    dtAdmissao: "2015-04-30",
    salario: 5300,
    turno: "Manhã",
    status: "Ativo",
    Series: "Ensino Médio",
    proxFeedback: "2024-11-22",
    observacoes: "Uso inovador de experimentos.",
    buttonAlert: "admin/dashboard/7",
    buttonEdit: "admin/dashboard/7",
  },
  {
    id: 8,
    disciplina: "Química",
    professor: "Patrícia Rocha",
    telefone: "(81) 93333-2222",
    email: "patricia.rocha@email.com",
    dtAdmissao: "2014-07-14",
    salario: 5400,
    turno: "Tarde",
    status: "Ativo",
    Series: "Ensino Médio",
    proxFeedback: "2024-12-10",
    observacoes: "Organiza feiras de ciências.",
    buttonAlert: "admin/dashboard/8",
    buttonEdit: "admin/dashboard/8",
  },
  {
    id: 9,
    disciplina: "Inglês",
    professor: "Roberto Dias",
    telefone: "(91) 92222-1111",
    email: "roberto.dias@email.com",
    dtAdmissao: "2013-10-20",
    salario: 5100,
    turno: "Noite",
    status: "Ativo",
    Series: "Fundamental e Médio",
    proxFeedback: "2025-01-05",
    observacoes: "Utiliza tecnologia na aula.",
    buttonAlert: "admin/dashboard/9",
    buttonEdit: "admin/dashboard/9",
  },
  {
    id: 10,
    disciplina: "Artes",
    professor: "Camila Batista",
    telefone: "(99) 91111-0000",
    email: "camila.batista@email.com",
    dtAdmissao: "2012-12-05",
    salario: 4900,
    turno: "Manhã",
    status: "Ativo",
    Series: "1º ao 9º",
    proxFeedback: "2025-02-15",
    observacoes: "Promove exposições de arte dos alunos.",
    buttonAlert: "admin/dashboard/10",
    buttonEdit: "admin/dashboard/10",
  },
];

export default rows;
