const rows = [
  {
    id: 1,
    nome: "João Silva",
    idade: 14,
    cpf: "123.456.789-01",
    genero: "Masculino",
    dtNascimento: "10/05/2009",
    nomeResponsavel: "Maria Silva",
    contatoResponsavel: "9876-5432",
    endereco: "Rua das Flores, 45",
    dtMatricula: "15/02/2023",
    statusMatricula: "Ativo",
    neceEspecial: "Nenhuma",
    observacoes: "Aluno participativo.",
    buttonEdit: "/admin/alunos/1",
  },
  {
    id: 2,
    nome: "Ana Souza",
    idade: 15,
    cpf: "234.567.890-12",
    genero: "Feminino",
    dtNascimento: "22/08/2008",
    nomeResponsavel: "Carlos Souza",
    contatoResponsavel: "9123-4567",
    endereco: "Av. Brasil, 101",
    dtMatricula: "10/03/2022",
    statusMatricula: "Ativo",
    neceEspecial: "Nenhuma",
    observacoes: "Boa aluna, dedicada.",
    buttonEdit: "/admin/alunos/2",
  },
  {
    id: 3,
    nome: "Pedro Oliveira",
    idade: 16,
    cpf: "345.678.901-23",
    genero: "Masculino",
    dtNascimento: "30/11/2007",
    nomeResponsavel: "Fernanda Oliveira",
    contatoResponsavel: "9987-6543",
    endereco: "Rua do Sol, 77",
    dtMatricula: "05/04/2021",
    statusMatricula: "Ativo",
    neceEspecial: "Déficit de atenção",
    observacoes: "Necessita suporte adicional.",
    buttonEdit: "/admin/alunos/3",
  },
  {
    id: 4,
    nome: "Mariana Costa",
    idade: 13,
    cpf: "456.789.012-34",
    genero: "Feminino",
    dtNascimento: "14/07/2010",
    nomeResponsavel: "Roberto Costa",
    contatoResponsavel: "9345-6789",
    endereco: "Rua Central, 29",
    dtMatricula: "20/06/2023",
    statusMatricula: "Ativo",
    neceEspecial: "Nenhuma",
    observacoes: "Excelente comportamento.",
    buttonEdit: "/admin/alunos/4",
  },
  {
    id: 5,
    nome: "Lucas Pereira",
    idade: 17,
    cpf: "567.890.123-45",
    genero: "Masculino",
    dtNascimento: "02/02/2006",
    nomeResponsavel: "Tatiane Pereira",
    contatoResponsavel: "9111-2233",
    endereco: "Rua Verde, 11",
    dtMatricula: "18/01/2020",
    statusMatricula: "Ativo",
    neceEspecial: "Dislexia",
    observacoes: "Acompanhamento pedagógico necessário.",
    buttonEdit: "/admin/alunos/5",
  },
  {
    id: 6,
    nome: "Beatriz Almeida",
    idade: 12,
    cpf: "678.901.234-56",
    genero: "Feminino",
    dtNascimento: "25/12/2011",
    nomeResponsavel: "José Almeida",
    contatoResponsavel: "9222-3344",
    endereco: "Rua Azul, 58",
    dtMatricula: "12/02/2024",
    statusMatricula: "Ativo",
    neceEspecial: "Nenhuma",
    observacoes: "Participa de atividades extracurriculares.",
    buttonEdit: "/admin/alunos/6",
  },
  {
    id: 7,
    nome: "Rafael Mendes",
    idade: 15,
    cpf: "789.012.345-67",
    genero: "Masculino",
    dtNascimento: "09/04/2008",
    nomeResponsavel: "Juliana Mendes",
    contatoResponsavel: "9333-4455",
    endereco: "Rua Amarela, 99",
    dtMatricula: "03/05/2021",
    statusMatricula: "Ativo",
    neceEspecial: "Nenhuma",
    observacoes: "Aluno tranquilo e disciplinado.",
    buttonEdit: "/admin/alunos/7",
  },
  {
    id: 8,
    nome: "Isabela Rocha",
    idade: 14,
    cpf: "890.123.456-78",
    genero: "Feminino",
    dtNascimento: "17/09/2009",
    nomeResponsavel: "Daniel Rocha",
    contatoResponsavel: "9444-5566",
    endereco: "Av. Paulista, 1234",
    dtMatricula: "25/07/2022",
    statusMatricula: "Ativo",
    neceEspecial: "Nenhuma",
    observacoes: "Ótimo desempenho acadêmico.",
    buttonEdit: "/admin/alunos/8",
  },
  {
    id: 9,
    nome: "Gustavo Fernandes",
    idade: 16,
    cpf: "901.234.567-89",
    genero: "Masculino",
    dtNascimento: "05/06/2007",
    nomeResponsavel: "Carla Fernandes",
    contatoResponsavel: "9555-6677",
    endereco: "Rua da Praia, 222",
    dtMatricula: "08/09/2020",
    statusMatricula: "Ativo",
    neceEspecial: "Autismo leve",
    observacoes: "Precisa de acompanhamento especial.",
    buttonEdit: "/admin/alunos/9",
  },
  {
    id: 10,
    nome: "Camila Ribeiro",
    idade: 13,
    cpf: "012.345.678-90",
    genero: "Feminino",
    dtNascimento: "11/03/2010",
    nomeResponsavel: "André Ribeiro",
    contatoResponsavel: "9666-7788",
    endereco: "Rua do Lago, 88",
    dtMatricula: "14/10/2023",
    statusMatricula: "Ativo",
    neceEspecial: "Nenhuma",
    observacoes: "Aluno novo, ainda em adaptação.",
    buttonEdit: "/admin/alunos/10",
  },
];

export default rows;
